# Generated by Django 2.2.4 on 2019-08-09 20:02

import bookkeeper.validators
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import organizations.base


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateField(default=datetime.date.today)),
                ('transaction_type', models.CharField(choices=[('INCOME', 'INCOME'), ('EXPENSE', 'EXPENSE')], max_length=9, validators=[bookkeeper.validators.validate_characters])),
                ('description', models.TextField(max_length=150, validators=[bookkeeper.validators.validate_characters])),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=20, validators=[bookkeeper.validators.check_negative_number])),
                ('name', models.CharField(max_length=30, validators=[bookkeeper.validators.validate_characters])),
                ('transaction_date', models.DateField(default=datetime.date.today)),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=20, validators=[bookkeeper.validators.check_negative_number])),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of the organization', max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('street_address', models.CharField(default='', max_length=100)),
                ('city', models.CharField(default='', max_length=100)),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
            },
            bases=(organizations.base.UnicodeMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Records',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=1000)),
                ('date', models.DateField(default=datetime.date.today)),
            ],
        ),
        migrations.CreateModel(
            name='CompanyUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(default='', max_length=1)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization_users', to='bookkeeper.Company')),
                ('permissions', models.ManyToManyField(blank=True, to='auth.Permission')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookkeeper_companyuser', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['organization', 'user'],
                'abstract': False,
                'unique_together': {('user', 'organization')},
            },
            bases=(organizations.base.UnicodeMixin, models.Model),
        ),
        migrations.CreateModel(
            name='CompanyOwner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to='bookkeeper.Company')),
                ('organization_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='bookkeeper.CompanyUser')),
            ],
            options={
                'abstract': False,
            },
            bases=(organizations.base.UnicodeMixin, models.Model),
        ),
        migrations.AddField(
            model_name='company',
            name='users',
            field=models.ManyToManyField(related_name='bookkeeper_company', through='bookkeeper.CompanyUser', to=settings.AUTH_USER_MODEL),
        ),
    ]
