# Generated by Django 2.2.4 on 2019-08-09 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookkeeper', '0002_book_organisation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='organisation',
        ),
    ]
